version: "3"

tasks:
  run:
    deps:
      - task: build
        silent: true
    dir: ./test/fixtures
    cmds:
      - ../../dist/pages_windows_amd64/pages.exe {{.CLI_ARGS}}

  build:
    cmds:
      - goreleaser build --snapshot --rm-dist --single-target

  release:
    cmds:
      - goreleaser release --snapshot --rm-dist
